### ISSUE TITLE
Add `useHotKeys` hook

### ISSUE THREAD

**Issue by anmol-kumar0815** [bigbinary/neeto-hotkeys#3]
Part of https://github.com/bigbinary/neeto-commons-frontend/issues/984

@anmol-kumar0815 _A

**Comment by sumanranjanpanda** [comment]
@Amaljith-K _a The issue is in the "in progress" column but is not assigned to anyone.

**Comment by Amaljith-K** [comment]
@deepakjosp _a please take care of this
